[package]
name = "raft"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
crossbeam = "0.8.4"
rand = "0.9.1"
log = "0.4.27"
env_logger = "0.11.8"
rand_distr = "0.5.1"
